name: Build macOS Executable with Spec

on:
  push:
    branches: [ "macOS" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'   # バージョンは変更可
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build with PyInstaller using spec file
      run: |
        : # または、直接ビルド
        pyinstaller PrimaryStock.py -n PrimaryStock-macOS-v-1.0.1 --target-architecture universal2

    - name: Create DMG Installer
      run: |
        brew install create-dmg
        mkdir dmg_source
        create-dmg \
          --volname "PrimaryStock-macOS-v-1.0.1 Installer" \
          --app-drop-link 350 120 \
          --filesystem "APFS" \
          "PrimaryStock-macOS-v-1.0.1.dmg" \
          dist/

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: macos-dmg-installer
        path: PrimaryStock-macOS-v-1.0.1.dmg